apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: outofthepark15226.azurecr.io/notification-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: notif-http
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-deployment
spec:
  ports:
    - name: notification-service
      port: 80
      targetPort: notif-http
  selector:
    app: notification-service
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: notification-service-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: notification-service.1c50b018f5784721b39b.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: notification-service-deployment
          servicePort: 80
        path: /notification-service(/|$)(.*)
      