apiVersion: v1
kind: Service
metadata:
  name: notification-service-deployment
spec:
  ports:
    - name: notification-service
      port: 80
      targetPort: notif-http
  selector:
    app: notification-service
  type: LoadBalancer
---
